# Code Generated by Sidekick is for learning and experimentation purposes only.
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "East US"
}
